#!/bin/sh

git clone --bare git@github.com:munjal/dotfiles.git ~$HOME/.cfg

git_mod()
{
    /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}

mkdir -p .config-backup

if git_mod checkout; then
    echo "Checked out config.";
else
    echo "Backing up pre-existing dot files.";
    git_mod checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .git_mod-backup/{}
fi;

git_mod checkout
git_mod config status.showUntrackedFiles no
